In [1]:
pip install currencyconverter

Requirement already satisfied: currencyconverter in ./.local/lib/python3.10/site-packages (0.17.13)
Note: you may need to restart the kernel to use updated packages.

In [71]:
import pandas as pd
import numpy as np
from currency_converter import CurrencyConverter
from currency_converter.currency_converter import RateNotFoundError
from datetime import date

In [4]:
df.columns

Index(['IMDB Ratings', 'IMDB Score', 'Content Rating', 'Date Released', 'year',
       'month', 'day of the week', 'Genres', 'Genre A', 'Genre B', 'Genre C',
       'Keywords', 'Keyword 1', 'Keyword 2', 'Keyword 3', 'Stars', 'Star 1',
       'Star 2', 'Star 3', 'Directors', 'Director 1', 'Director 2',
       'Director 3', 'Writers', 'Writer 1', 'Writer 2', 'Writer 3', 'Runtime',
       'Nominations', 'Awards', 'Estimated Budget', 'Budget Currency',
       'Gross Revenue US&Canada USD', 'Opening Weekend Revenue US&Canada USD',
       'Gross Revenue Worldwide USD', 'RT_audience_score',
       'RT_tomatometer_score', 'RT_audience_#reviews',
       'RT_tomatometer_#reviews', 'Producer', 'Prod1', 'Prod2', 'Prod3',
       'Prod4', 'Prod5', 'Prod6', 'Dom_Profit', 'Dom_ROI'],
      dtype='object')

In [106]:
#Initiate currency converter function and read dataframe
c = CurrencyConverter()
df = pd.read_csv('df_movie.csv', index_col = ['Name'])

# Function to convert to USD
# Modify the conversion function to handle missing rates
def convert_to_usd(row):
    if row['Budget Currency'] == '$':
        return row['Estimated Budget']
    elif row['Budget Currency'] == '£':
        return c.convert(row['Estimated Budget'], 'GBP', 'USD', date=date(2013, 3, 21))
    elif row['Budget Currency'] == '€':
        return c.convert(row['Estimated Budget'], 'EUR', 'USD')
    elif row['Budget Currency'] == '₹':
        return c.convert(row['Estimated Budget'], 'INR', 'USD')
    elif row['Budget Currency'] == '₩':
        return c.convert(row['Estimated Budget'], 'KRW', 'USD')
    elif row['Budget Currency'] == '¥':
        return c.convert(row['Estimated Budget'], 'JPY', 'USD')

# Apply the conversion function to create the 'Budget Converted' column
df['Budget Converted'] = df.apply(convert_to_usd, axis=1) 

# Display the updated DataFrame
print(df)

                              IMDB Ratings  IMDB Score Content Rating  \
Name
Avatar: The Way of Water            469417         7.6             PG
Puss in Boots: The Last Wish        161291         7.8             PG
Babylon                             153248         7.1            18A
A Man Called Otto                   141943         7.5              G
M3GAN                               132495         6.4            14A
...                                    ...         ...            ...
Mean Streets                        116925         7.2            18+
American Graffiti                    96624         7.4             PG
Live and Let Die                    113572         6.7            14+
Deliverance                         117328         7.7            18A
The Godfather                      1968971         9.2            18A

                             Date Released  year  month  day of the week  \
Name
Avatar: The Way of Water        2022-12-16  2022     12                4
Puss in Boots: The Last Wish    2022-12-21  2022     12                2
Babylon                         2022-12-23  2022     12                4
A Man Called Otto               2023-01-13  2023      1                4
M3GAN                           2023-01-06  2023      1                4
...                                    ...   ...    ...              ...
Mean Streets                    1974-03-08  1974      3                4
American Graffiti               1973-08-11  1973      8                5
Live and Let Die                1973-06-27  1973      6                2
Deliverance                     1972-10-14  1972     10                5
The Godfather                   1972-03-24  1972      3                4

                                                          Genres    Genre A  \
Name
Avatar: The Way of Water        ['Action' 'Adventure' 'Fantasy']     Action
Puss in Boots: The Last Wish  ['Animation' 'Adventure' 'Comedy']  Animation
Babylon                             ['Comedy' 'Drama' 'History']     Comedy
A Man Called Otto                             ['Comedy' 'Drama']     Comedy
M3GAN                             ['Horror' 'Sci-Fi' 'Thriller']     Horror
...                                                          ...        ...
Mean Streets                        ['Crime' 'Drama' 'Thriller']      Crime
American Graffiti                             ['Comedy' 'Drama']     Comedy
Live and Let Die               ['Action' 'Adventure' 'Thriller']     Action
Deliverance                     ['Adventure' 'Drama' 'Thriller']  Adventure
The Godfather                                  ['Crime' 'Drama']      Crime

                                Genre B  ...  \
Name                                     ...
Avatar: The Way of Water      Adventure  ...
Puss in Boots: The Last Wish  Adventure  ...
Babylon                           Drama  ...
A Man Called Otto                 Drama  ...
M3GAN                            Sci-Fi  ...
...                                 ...  ...
Mean Streets                      Drama  ...
American Graffiti                 Drama  ...
Live and Let Die              Adventure  ...
Deliverance                       Drama  ...
The Godfather                     Drama  ...

                                                                       Producer  \
Name
Avatar: The Way of Water                               James Cameron,Jon Landau
Puss in Boots: The Last Wish                                         Mark Swift
Babylon                              Marc Platt,Matthew Plouffe,Olivia Hamilton
A Man Called Otto             Fredrik Wikström,Rita Wilson,Tom Hanks,Gary Go...
M3GAN                                     Jason Blum,James Wan,Couper Samuelson
...                                                                         ...
Mean Streets                                                 Jonathan T. Taplin
American Graffiti                               Francis Ford Coppola,Gary Kurtz
Live and Let Die                              Albert R. Broccoli,Harry Saltzman
Deliverance                                                        John Boorman
The Godfather                                                   Albert S. Ruddy

                                             Prod1            Prod2  \
Name
Avatar: The Way of Water             James Cameron       Jon Landau
Puss in Boots: The Last Wish            Mark Swift              NaN
Babylon                                 Marc Platt  Matthew Plouffe
A Man Called Otto                 Fredrik Wikström      Rita Wilson
M3GAN                                   Jason Blum        James Wan
...                                            ...              ...
Mean Streets                    Jonathan T. Taplin              NaN
American Graffiti             Francis Ford Coppola       Gary Kurtz
Live and Let Die                Albert R. Broccoli   Harry Saltzman
Deliverance                           John Boorman              NaN
The Godfather                      Albert S. Ruddy              NaN

                                         Prod3          Prod4 Prod5 Prod6  \
Name
Avatar: The Way of Water                   NaN            NaN   NaN   NaN
Puss in Boots: The Last Wish               NaN            NaN   NaN   NaN
Babylon                        Olivia Hamilton            NaN   NaN   NaN
A Man Called Otto                    Tom Hanks  Gary Goetzman   NaN   NaN
M3GAN                         Couper Samuelson            NaN   NaN   NaN
...                                        ...            ...   ...   ...
Mean Streets                               NaN            NaN   NaN   NaN
American Graffiti                          NaN            NaN   NaN   NaN
Live and Let Die                           NaN            NaN   NaN   NaN
Deliverance                                NaN            NaN   NaN   NaN
The Godfather                              NaN            NaN   NaN   NaN

                               Dom_Profit    Dom_ROI Budget Converted
Name
Avatar: The Way of Water      334075767.0   0.954502      350000000.0
Puss in Boots: The Last Wish   95535345.0   1.061504       90000000.0
Babylon                       -94648545.0  -0.860441      110000000.0
A Man Called Otto              14267657.0   0.285353       50000000.0
M3GAN                          83043350.0   6.920279       12000000.0
...                                   ...        ...              ...
Mean Streets                    -467355.0  -0.934710         500000.0
American Graffiti                     NaN        NaN              NaN
Live and Let Die                      NaN        NaN              NaN
Deliverance                           NaN        NaN              NaN
The Godfather                 130381073.0  21.730179        6000000.0

[2045 rows x 49 columns]

In [108]:
budget_currency_counts = df['Budget Currency'].value_counts()

# Display the counts
print(budget_currency_counts)

$          1810
unknown     194
£            17
€            11
₹             7
₩             2
¥             1
D             1
C             1
F             1
Name: Budget Currency, dtype: int64

In [114]:
#Find some movies where currency is not USD

# Filter the DataFrame for rows where 'Budget Currency' is british pounds
unknown_currency_rows = df[df['Budget Currency']=='¥']

# Display unique values or counts in the 'Estimated Budget' column within the subset
unknown_currency_rows

,IMDB Ratings,IMDB Score,Content Rating,Date Released,year,month,day of the week,Genres,Genre A,Genre B,...,Producer,Prod1,Prod2,Prod3,Prod4,Prod5,Prod6,Dom_Profit,Dom_ROI,Budget Converted
Name,,,,,,,,,,,,,,,,,,,,,
Paprika,92719,7.7,PG,2006-11-25,2006,11,5,['Animation' 'Drama' 'Fantasy'],Animation,Drama,...,"Jungo Maruta,Masao Takiyama",Jungo Maruta,Masao Takiyama,NaN,NaN,NaN,NaN,-299117733.0,-0.997059,1.988756e+06

In [115]:
#Check that it works -> Paprika not 30M anymore!
df[df['Estimated Budget']==300000000]

,IMDB Ratings,IMDB Score,Content Rating,Date Released,year,month,day of the week,Genres,Genre A,Genre B,...,Producer,Prod1,Prod2,Prod3,Prod4,Prod5,Prod6,Dom_Profit,Dom_ROI,Budget Converted
Name,,,,,,,,,,,,,,,,,,,,,
Pirates of the Caribbean: At World's End,681036,7.1,PG,2007-05-25,2007,5,4,['Action' 'Adventure' 'Fantasy'],Action,Adventure,...,Jerry Bruckheimer,Jerry Bruckheimer,NaN,NaN,NaN,NaN,NaN,9420425.0,0.031401,3.000000e+08
Paprika,92719,7.7,PG,2006-11-25,2006,11,5,['Animation' 'Drama' 'Fantasy'],Animation,Drama,...,"Jungo Maruta,Masao Takiyama",Jungo Maruta,Masao Takiyama,NaN,NaN,NaN,NaN,-299117733.0,-0.997059,1.988756e+06

In [100]:
#Check that it works -> Paprika not 30M anymore!
df[df['Budget Converted']==300000000]

,IMDB Ratings,IMDB Score,Content Rating,Date Released,year,month,day of the week,Genres,Genre A,Genre B,...,Prod1,Prod2,Prod3,Prod4,Prod5,Prod6,Dom_Profit,Dom_ROI,Budget Currency Code,Budget Converted
Name,,,,,,,,,,,,,,,,,,,,,
Pirates of the Caribbean: At World's End,681036,7.1,PG,2007-05-25,2007,5,4,['Action' 'Adventure' 'Fantasy'],Action,Adventure,...,Jerry Bruckheimer,NaN,NaN,NaN,NaN,NaN,9420425.0,0.031401,USD,300000000.0

In [116]:
# Retain only index and 'Budget Converted' column, drop other columns
df = df[['Budget Converted']]

# Display the updated DataFrame
print(df)

                              Budget Converted
Name
Avatar: The Way of Water           350000000.0
Puss in Boots: The Last Wish        90000000.0
Babylon                            110000000.0
A Man Called Otto                   50000000.0
M3GAN                               12000000.0
...                                        ...
Mean Streets                          500000.0
American Graffiti                          NaN
Live and Let Die                           NaN
Deliverance                                NaN
The Godfather                        6000000.0

[2045 rows x 1 columns]

In [105]:
#Convert df to csv for export and use in master file
df.to_csv('budget_converted.csv', index=False)  # Save the updated DataFrame to a CSV file