In [1]:
pip install currencyconverter

Requirement already satisfied: currencyconverter in ./.local/lib/python3.10/site-packages (0.17.13)
Note: you may need to restart the kernel to use updated packages.

In [71]:
import pandas as pd
import numpy as np
from currency_converter import CurrencyConverter
from currency_converter.currency_converter import RateNotFoundError
from datetime import date

In [4]:
df.columns

Index(['IMDB Ratings', 'IMDB Score', 'Content Rating', 'Date Released', 'year',
       'month', 'day of the week', 'Genres', 'Genre A', 'Genre B', 'Genre C',
       'Keywords', 'Keyword 1', 'Keyword 2', 'Keyword 3', 'Stars', 'Star 1',
       'Star 2', 'Star 3', 'Directors', 'Director 1', 'Director 2',
       'Director 3', 'Writers', 'Writer 1', 'Writer 2', 'Writer 3', 'Runtime',
       'Nominations', 'Awards', 'Estimated Budget', 'Budget Currency',
       'Gross Revenue US&Canada USD', 'Opening Weekend Revenue US&Canada USD',
       'Gross Revenue Worldwide USD', 'RT_audience_score',
       'RT_tomatometer_score', 'RT_audience_#reviews',
       'RT_tomatometer_#reviews', 'Producer', 'Prod1', 'Prod2', 'Prod3',
       'Prod4', 'Prod5', 'Prod6', 'Dom_Profit', 'Dom_ROI'],
      dtype='object')

In [103]:
#Initiate currency converter function and read dataframe
c = CurrencyConverter()
df = pd.read_csv('df_movie.csv', index_col = ['Name'])


# Function to convert currency symbol to 3-letter code
def convert_currency_symbol_to_code(currency_symbol):
    symbol_to_code = {
        '$': 'USD',
        '¬£': 'GBP',
        '‚Ç¨': 'EUR',
        '‚Çπ': 'INR',
        '‚Ç©': 'KRW',
        '¬•': 'JPY'
        # Add more currency symbols and their corresponding codes as needed
    }
    if isinstance(currency_symbol, pd.Series):
        return currency_symbol.map(symbol_to_code).fillna('Unknown')
    return symbol_to_code.get(currency_symbol, 'Unknown')

# Create 'Budget Currency Code' column with 3-letter codes
df['Budget Currency Code'] = convert_currency_symbol_to_code(df['Budget Currency'])

# Function to convert to USD
# Modify the conversion function to handle missing rates
def convert_to_usd(row):
    if row['Budget Currency'] == '$':
        return row['Estimated Budget']
    elif row['Budget Currency'] == '¬£':
        return c.convert(row['Estimated Budget'], 'GBP', 'USD', date=date(2013, 3, 21))
    elif row['Budget Currency'] == '‚Ç¨':
        return c.convert(row['Estimated Budget'], 'EUR', 'USD')
    elif row['Budget Currency'] == '‚Çπ':
        return c.convert(row['Estimated Budget'], 'INR', 'USD')
    elif row['Budget Currency'] == '‚Ç©':
        return c.convert(row['Estimated Budget'], 'KRW', 'USD')
    elif row['Budget Currency'] == '¬•':
        return c.convert(row['Estimated Budget'], 'JPY', 'USD')

# Apply the conversion function to create the 'Budget Converted' column
df['Budget Converted'] = df.apply(convert_to_usd, axis=1) 

# Display the updated DataFrame
print(df)

                              IMDB Ratings  IMDB Score Content Rating  \
Name
Avatar: The Way of Water            469417         7.6             PG
Puss in Boots: The Last Wish        161291         7.8             PG
Babylon                             153248         7.1            18A
A Man Called Otto                   141943         7.5              G
M3GAN                               132495         6.4            14A
...                                    ...         ...            ...
Mean Streets                        116925         7.2            18+
American Graffiti                    96624         7.4             PG
Live and Let Die                    113572         6.7            14+
Deliverance                         117328         7.7            18A
The Godfather                      1968971         9.2            18A

                             Date Released  year  month  day of the week  \
Name
Avatar: The Way of Water        2022-12-16  2022     12                4
Puss in Boots: The Last Wish    2022-12-21  2022     12                2
Babylon                         2022-12-23  2022     12                4
A Man Called Otto               2023-01-13  2023      1                4
M3GAN                           2023-01-06  2023      1                4
...                                    ...   ...    ...              ...
Mean Streets                    1974-03-08  1974      3                4
American Graffiti               1973-08-11  1973      8                5
Live and Let Die                1973-06-27  1973      6                2
Deliverance                     1972-10-14  1972     10                5
The Godfather                   1972-03-24  1972      3                4

                                                          Genres    Genre A  \
Name
Avatar: The Way of Water        ['Action' 'Adventure' 'Fantasy']     Action
Puss in Boots: The Last Wish  ['Animation' 'Adventure' 'Comedy']  Animation
Babylon                             ['Comedy' 'Drama' 'History']     Comedy
A Man Called Otto                             ['Comedy' 'Drama']     Comedy
M3GAN                             ['Horror' 'Sci-Fi' 'Thriller']     Horror
...                                                          ...        ...
Mean Streets                        ['Crime' 'Drama' 'Thriller']      Crime
American Graffiti                             ['Comedy' 'Drama']     Comedy
Live and Let Die               ['Action' 'Adventure' 'Thriller']     Action
Deliverance                     ['Adventure' 'Drama' 'Thriller']  Adventure
The Godfather                                  ['Crime' 'Drama']      Crime

                                Genre B  ...                 Prod1  \
Name                                     ...
Avatar: The Way of Water      Adventure  ...         James Cameron
Puss in Boots: The Last Wish  Adventure  ...            Mark Swift
Babylon                           Drama  ...            Marc Platt
A Man Called Otto                 Drama  ...      Fredrik Wikstr√∂m
M3GAN                            Sci-Fi  ...            Jason Blum
...                                 ...  ...                   ...
Mean Streets                      Drama  ...    Jonathan T. Taplin
American Graffiti                 Drama  ...  Francis Ford Coppola
Live and Let Die              Adventure  ...    Albert R. Broccoli
Deliverance                       Drama  ...          John Boorman
The Godfather                     Drama  ...       Albert S. Ruddy

                                        Prod2             Prod3  \
Name
Avatar: The Way of Water           Jon Landau               NaN
Puss in Boots: The Last Wish              NaN               NaN
Babylon                       Matthew Plouffe   Olivia Hamilton
A Man Called Otto                 Rita Wilson         Tom Hanks
M3GAN                               James Wan  Couper Samuelson
...                                       ...               ...
Mean Streets                              NaN               NaN
American Graffiti                  Gary Kurtz               NaN
Live and Let Die               Harry Saltzman               NaN
Deliverance                               NaN               NaN
The Godfather                             NaN               NaN

                                      Prod4 Prod5 Prod6   Dom_Profit  \
Name
Avatar: The Way of Water                NaN   NaN   NaN  334075767.0
Puss in Boots: The Last Wish            NaN   NaN   NaN   95535345.0
Babylon                                 NaN   NaN   NaN  -94648545.0
A Man Called Otto             Gary Goetzman   NaN   NaN   14267657.0
M3GAN                                   NaN   NaN   NaN   83043350.0
...                                     ...   ...   ...          ...
Mean Streets                            NaN   NaN   NaN    -467355.0
American Graffiti                       NaN   NaN   NaN          NaN
Live and Let Die                        NaN   NaN   NaN          NaN
Deliverance                             NaN   NaN   NaN          NaN
The Godfather                           NaN   NaN   NaN  130381073.0

                                Dom_ROI Budget Currency Code Budget Converted
Name
Avatar: The Way of Water       0.954502                  USD      350000000.0
Puss in Boots: The Last Wish   1.061504                  USD       90000000.0
Babylon                       -0.860441                  USD      110000000.0
A Man Called Otto              0.285353                  USD       50000000.0
M3GAN                          6.920279                  USD       12000000.0
...                                 ...                  ...              ...
Mean Streets                  -0.934710                  USD         500000.0
American Graffiti                   NaN              Unknown              NaN
Live and Let Die                    NaN              Unknown              NaN
Deliverance                         NaN              Unknown              NaN
The Godfather                 21.730179                  USD        6000000.0

[2045 rows x 50 columns]

In [92]:
budget_currency_counts = df['Budget Currency Code'].value_counts()

# Display the counts
print(budget_currency_counts)

USD        1810
Unknown     197
GBP          17
EUR          11
INR           7
KRW           2
JPY           1
Name: Budget Currency Code, dtype: int64

In [104]:
#df = pd.read_csv('df_movie.csv', index_col = ['Name'])

#Find some movies where currency is not USD

# Filter the DataFrame for rows where 'Budget Currency' is 'unknown'
unknown_currency_rows = df[df['Budget Currency']=='¬£']

# Display unique values or counts in the 'Estimated Budget' column within the subset
unknown_currency_rows

,IMDB Ratings,IMDB Score,Content Rating,Date Released,year,month,day of the week,Genres,Genre A,Genre B,...,Prod1,Prod2,Prod3,Prod4,Prod5,Prod6,Dom_Profit,Dom_ROI,Budget Currency Code,Budget Converted
Name,,,,,,,,,,,,,,,,,,,,,
My Week with Marilyn,89030,6.9,14A,2011-11-25,2011,11,4,['Biography' 'Drama'],Biography,Drama,...,David Parfitt,Harvey Weinstein,NaN,NaN,NaN,NaN,8200347.0,1.281304,GBP,9.701638e+06
Tinker Tailor Soldier Spy,209710,7.0,14A,2011-09-16,2011,9,4,['Drama' 'Mystery' 'Thriller'],Drama,Mystery,...,Tim Bevan,Eric Fellner,Robyn Slovo,NaN,NaN,NaN,4149393.0,0.207470,GBP,3.031762e+07
The Inbetweeners Movie,85723,6.7,18A,2021-02-05,2021,2,4,['Comedy'],Comedy,none,...,Christopher Young,NaN,NaN,NaN,NaN,NaN,-3464000.0,-0.989714,GBP,5.305583e+06
Eastern Promises,256285,7.6,18A,2007-09-14,2007,9,4,['Crime' 'Drama' 'Thriller'],Crime,Drama,...,Paul Webster,Robert Lantos,NaN,NaN,NaN,NaN,-7734000.0,-0.309360,GBP,3.789702e+07
Sunshine,262719,7.2,14A,2007-07-27,2007,7,4,['Sci-Fi' 'Thriller'],Sci-Fi,Thriller,...,Andrew Macdonald,NaN,NaN,NaN,NaN,NaN,-22324247.0,-0.858625,GBP,3.941290e+07
Hot Fuzz,527244,7.8,14A,2007-04-20,2007,4,4,['Action' 'Comedy' 'Mystery'],Action,Comedy,...,Tim Bevan,Nira Park,Eric Fellner,NaN,NaN,NaN,15637265.0,1.954658,GBP,1.212705e+07
This Is England,127199,7.7,18A,2007-04-27,2007,4,4,['Crime' 'Drama'],Crime,Drama,...,Mark Herbert,NaN,NaN,NaN,NaN,NaN,-1170621.0,-0.780414,GBP,2.273821e+06
The Queen,115023,7.3,PG,2006-10-20,2006,10,4,['Biography' 'Drama'],Biography,Drama,...,Andy Harries,Christine Langan,Tracey Seaward,NaN,NaN,NaN,46641711.0,4.759358,GBP,1.485563e+07
The Descent,241727,7.2,18A,2006-08-04,2006,8,4,['Adventure' 'Horror' 'Thriller'],Adventure,Horror,...,Christian Colson,NaN,NaN,NaN,NaN,NaN,22524456.0,6.435559,GBP,5.305583e+06
Layer Cake,191732,7.3,18A,2005-06-10,2005,6,4,['Action' 'Crime' 'Drama'],Action,Crime,...,Adam Bohling,David Reid,Matthew Vaughn,NaN,NaN,NaN,-1660043.0,-0.415011,GBP,6.063524e+06
Shaun of the Dead,583846,7.9,18A,2004-04-09,2004,4,4,['Comedy' 'Horror'],Comedy,Horror,...,Nira Park,NaN,NaN,NaN,NaN,NaN,9542874.0,2.385718,GBP,6.063524e+06
Bend It Like Beckham,115241,6.7,PG,2002-04-12,2002,4,4,['Comedy' 'Drama' 'Romance'],Comedy,Drama,...,Deepak Nayar,Gurinder Chadha,NaN,NaN,NaN,NaN,29043290.0,8.297706,GBP,5.305824e+06
Snatch,892918,8.2,16+,2001-01-19,2001,1,4,['Comedy' 'Crime'],Comedy,Crime,...,Matthew Vaughn,NaN,NaN,NaN,NaN,NaN,24328156.0,4.054693,GBP,9.095286e+06
"Lock, Stock and Two Smoking Barrels",606620,8.1,16+,1999-03-05,1999,3,4,['Action' 'Comedy' 'Crime'],Action,Comedy,...,Matthew Vaughn,NaN,NaN,NaN,NaN,NaN,2793929.0,2.910343,GBP,1.455246e+06
Trainspotting,714241,8.1,R,1996-07-26,1996,7,4,['Drama'],Drama,none,...,Andrew Macdonald,NaN,NaN,NaN,NaN,NaN,14991080.0,9.994053,GBP,2.273821e+06
Hellraiser,137701,6.9,R,1987-09-18,1987,9,4,['Horror' 'Thriller'],Horror,Thriller,...,Christopher Figg,NaN,NaN,NaN,NaN,NaN,13564027.0,13.564027,GBP,1.515881e+06
Monty Python and the Holy Grail,562005,8.2,PG,1975-05-25,1975,5,6,['Adventure' 'Comedy' 'Fantasy'],Adventure,Comedy,...,Mark Forstater,NaN,NaN,NaN,NaN,NaN,1598121.0,6.961215,GBP,3.480084e+05

In [99]:
#Check that it works -> Paprika not 30M anymore!
df[df['Estimated Budget']==300000000]

,IMDB Ratings,IMDB Score,Content Rating,Date Released,year,month,day of the week,Genres,Genre A,Genre B,...,Prod1,Prod2,Prod3,Prod4,Prod5,Prod6,Dom_Profit,Dom_ROI,Budget Currency Code,Budget Converted
Name,,,,,,,,,,,,,,,,,,,,,
Pirates of the Caribbean: At World's End,681036,7.1,PG,2007-05-25,2007,5,4,['Action' 'Adventure' 'Fantasy'],Action,Adventure,...,Jerry Bruckheimer,NaN,NaN,NaN,NaN,NaN,9420425.0,0.031401,USD,3.000000e+08
Paprika,92719,7.7,PG,2006-11-25,2006,11,5,['Animation' 'Drama' 'Fantasy'],Animation,Drama,...,Jungo Maruta,Masao Takiyama,NaN,NaN,NaN,NaN,-299117733.0,-0.997059,JPY,1.988756e+06

In [100]:
df[df['Budget Converted']==300000000]

,IMDB Ratings,IMDB Score,Content Rating,Date Released,year,month,day of the week,Genres,Genre A,Genre B,...,Prod1,Prod2,Prod3,Prod4,Prod5,Prod6,Dom_Profit,Dom_ROI,Budget Currency Code,Budget Converted
Name,,,,,,,,,,,,,,,,,,,,,
Pirates of the Caribbean: At World's End,681036,7.1,PG,2007-05-25,2007,5,4,['Action' 'Adventure' 'Fantasy'],Action,Adventure,...,Jerry Bruckheimer,NaN,NaN,NaN,NaN,NaN,9420425.0,0.031401,USD,300000000.0

In [101]:
# Retain only index and 'Budget Converted' column, drop other columns
df = df[['Budget Converted']]

# Display the updated DataFrame
print(df)

                              Budget Converted
Name
Avatar: The Way of Water           350000000.0
Puss in Boots: The Last Wish        90000000.0
Babylon                            110000000.0
A Man Called Otto                   50000000.0
M3GAN                               12000000.0
...                                        ...
Mean Streets                          500000.0
American Graffiti                          NaN
Live and Let Die                           NaN
Deliverance                                NaN
The Godfather                        6000000.0

[2045 rows x 1 columns]

In [105]:
#Convert df to csv for export and use in master file
df.to_csv('budget_converted.csv', index=False)  # Save the updated DataFrame to a CSV file